### PR TITLE
Wraps long lines in example codes

### PR DESCRIPTION
**Pull request by paniash**
This PR is a fix for #150 where if the line is long enough, gets wrapped to the next line. Thanks to @Vismai-Khanderao for the fix-suggestion.

### CODE REVIEW

**Comment by Vismai-Khanderao** [comment]
Is there a simple method to apply the change to all the problems for consistency/future proofing?

**Comment by paniash** [comment]
We could add a test perhaps.

**Review by ali-ramadhan — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
Thanks for the fix guys!

> Is there a simple method to apply the change to all the problems for consistency/future proofing?

Hmmm right now I guess we're applying a bunch of styles manually. Maybe we should create a new CSS class like `example-block` that applies all the styles (including `white-space:pre-wrap`) and just use `class="example-block"`?

**Comment by paniash** [comment]
> Hmmm right now I guess we're applying a bunch of styles manually. Maybe we should create a new CSS class like `example-block` that applies all the styles (including `white-space:pre-wrap`) and just use `class="example-block"`?

I think that's a good idea. I'll keep the PR open for now.

**Comment by ali-ramadhan** [comment]
Ah I'm okay with merging this since it's an improvement and we can go for a new CSS class in a new PR (unless you'd rather do it in this PR).

**Comment by paniash** [comment]
@ali-ramadhan Sure! New PR it is. :-)

**Pull request merged**
